# Generated by Django 2.2.5 on 2019-12-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playoff_app', '0002_auto_20191230_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekly_picks',
            name='away',
            field=models.CharField(choices=[('BAL', 'Baltimore'), ('KC', 'Kansas City'), ('NE', 'New England'), ('HOU', 'Houston'), ('BUF', 'Buffalo'), ('Ten', 'Tennessee'), ('SF', 'San Francisco'), ('GB', 'Green Bay'), ('NO', 'New Orleans'), ('Phi', 'Philadelphia'), ('SEA', 'Seattle'), ('Min', 'Minnesota')], max_length=20),
        ),
        migrations.AlterField(
            model_name='weekly_picks',
            name='home',
            field=models.CharField(choices=[('BAL', 'Baltimore'), ('KC', 'Kansas City'), ('NE', 'New England'), ('HOU', 'Houston'), ('BUF', 'Buffalo'), ('Ten', 'Tennessee'), ('SF', 'San Francisco'), ('GB', 'Green Bay'), ('NO', 'New Orleans'), ('Phi', 'Philadelphia'), ('SEA', 'Seattle'), ('Min', 'Minnesota')], max_length=20),
        ),
        migrations.AlterField(
            model_name='weekly_picks',
            name='week',
            field=models.CharField(choices=[('WC', 'Wildcard'), ('DIV', 'Division'), ('CON', 'Conference'), ('SB', 'Superbowl')], max_length=3),
        ),
    ]
