# Generated by Django 2.2.5 on 2019-12-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playoff_app', '0003_auto_20191230_1012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ladder_Picks',
            new_name='Ladder_Pick',
        ),
        migrations.RenameModel(
            old_name='Playoff_Teams',
            new_name='Playoff_Team',
        ),
        migrations.RenameModel(
            old_name='Weekly_Picks',
            new_name='Weekly_Pick',
        ),
    ]
