# Generated by Django 2.2.5 on 2020-01-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playoff_app', '0005_auto_20191230_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='playoff_team',
            name='next_game',
            field=models.CharField(choices=[('AFC_WC1', 'Game1'), ('AFC_WC2', 'Game2'), ('NFC_WC1', 'Game3'), ('NFC_WC2', 'Game4'), ('AFC_DIV1', 'Game5'), ('AFC_DIV2', 'Game6'), ('NFC_DIV1', 'Game7'), ('NFC_DIV2', 'Game8'), ('AFC_Championship', 'Game9'), ('NFC_Championship', 'Game10'), ('Superbowl', 'Game11'), ('BYE', 'BYE')], default='BYE', max_length=3),
        ),
    ]
