# Generated by Django 2.2.1 on 2020-01-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playoff_app', '0009_auto_20200103_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game_schedule',
            options={'ordering': ('game_num',)},
        ),
    ]
