# Generated by Django 2.2.1 on 2020-01-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playoff_app', '0010_auto_20200103_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game_schedule',
            options={'ordering': ('day', 'game_num')},
        ),
        migrations.AddField(
            model_name='game_schedule',
            name='day',
            field=models.CharField(choices=[('Sat', 'Sat'), ('Sun', 'Sun')], default='Sat', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game_schedule',
            name='division',
            field=models.CharField(choices=[('AFC', 'AFC'), ('NFC', 'NFC')], default='AFC', max_length=4),
            preserve_default=False,
        ),
    ]
