# Generated by Django 2.2.1 on 2020-01-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playoff_app', '0011_auto_20200103_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_schedule',
            name='weekend',
            field=models.CharField(choices=[('Wildcard', 'Wildcard'), ('Division', 'Division'), ('Conference', 'Conference'), ('Superbowl', 'Superbowl')], default='Wildcard', max_length=20),
            preserve_default=False,
        ),
    ]
