# Generated by Django 2.2.5 on 2020-01-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playoff_app', '0012_game_schedule_weekend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_schedule',
            name='away',
            field=models.CharField(choices=[('Baltimore', 'Baltimore'), ('Kansas City', 'Kansas City'), ('New England', 'New England'), ('Houston', 'Houston'), ('Buffalo', 'Buffalo'), ('Tennessee', 'Tennessee'), ('San Francisco', 'San Francisco'), ('Green Bay', 'Green Bay'), ('New Orleans', 'New Orleans'), ('Philadelphia', 'Philadelphia'), ('Seattle', 'Seattle'), ('Minnesota', 'Minnesota')], max_length=20),
        ),
        migrations.AlterField(
            model_name='game_schedule',
            name='dog',
            field=models.CharField(choices=[('Baltimore', 'Baltimore'), ('Kansas City', 'Kansas City'), ('New England', 'New England'), ('Houston', 'Houston'), ('Buffalo', 'Buffalo'), ('Tennessee', 'Tennessee'), ('San Francisco', 'San Francisco'), ('Green Bay', 'Green Bay'), ('New Orleans', 'New Orleans'), ('Philadelphia', 'Philadelphia'), ('Seattle', 'Seattle'), ('Minnesota', 'Minnesota')], max_length=20),
        ),
        migrations.AlterField(
            model_name='game_schedule',
            name='home',
            field=models.CharField(choices=[('Baltimore', 'Baltimore'), ('Kansas City', 'Kansas City'), ('New England', 'New England'), ('Houston', 'Houston'), ('Buffalo', 'Buffalo'), ('Tennessee', 'Tennessee'), ('San Francisco', 'San Francisco'), ('Green Bay', 'Green Bay'), ('New Orleans', 'New Orleans'), ('Philadelphia', 'Philadelphia'), ('Seattle', 'Seattle'), ('Minnesota', 'Minnesota')], max_length=20),
        ),
        migrations.AlterField(
            model_name='weekly_pick',
            name='away',
            field=models.CharField(choices=[('Baltimore', 'Baltimore'), ('Kansas City', 'Kansas City'), ('New England', 'New England'), ('Houston', 'Houston'), ('Buffalo', 'Buffalo'), ('Tennessee', 'Tennessee'), ('San Francisco', 'San Francisco'), ('Green Bay', 'Green Bay'), ('New Orleans', 'New Orleans'), ('Philadelphia', 'Philadelphia'), ('Seattle', 'Seattle'), ('Minnesota', 'Minnesota')], max_length=20),
        ),
        migrations.AlterField(
            model_name='weekly_pick',
            name='home',
            field=models.CharField(choices=[('Baltimore', 'Baltimore'), ('Kansas City', 'Kansas City'), ('New England', 'New England'), ('Houston', 'Houston'), ('Buffalo', 'Buffalo'), ('Tennessee', 'Tennessee'), ('San Francisco', 'San Francisco'), ('Green Bay', 'Green Bay'), ('New Orleans', 'New Orleans'), ('Philadelphia', 'Philadelphia'), ('Seattle', 'Seattle'), ('Minnesota', 'Minnesota')], max_length=20),
        ),
    ]
